defaults: &defaults
  docker:
    - image: circleci/node:8.9.4-browsers

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      - persist_to_workspace:
          root: .
          paths:
            - umd
            - es
            - lib

  test:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: .

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: sudo npm install -g greenkeeper-lockfile@1
      - run: greenkeeper-lockfile-update

      # run tests!
      - run: npm run test

      - run: greenkeeper-lockfile-upload

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - test:
          requires:
            - build
